id: '17095171707750.6596189512095136'
kind: folder
name: Project
nameConfigured: true
steps:
  - id: '17095171707740.7851855291891716'
    type: draft
    name: newStep
    params: []
    level: 0
    fallthroughError: false
    isChanged: false
mode: manual
modeConfigured: false
parentPageId: '1'
parentId: null
config:
  shouldConfirm: false
  confirmMessage: Are you sure you'd like to proceed with "{{actions.Project.name}}"?
  showSuccessToast: false
  successToast: Action "{{actions.Project.name}}" successfully executed
  successToastDuration: '3000'
  successToastHideByClick: false
  showErrorToast: true
  errorToast: Action "{{actions.Project.name}}" has failed
  errorToastDuration: '3000'
  errorToastHideByClick: false
  delay: '0'
  runWhenFirstReferenced: true
  preserveStateOnPageChange: false
selected: false
